spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: root
    
  #redis环境
  redis:
    database: 0
    host: 192.168.1.106
    port: 6379
  
  #elasticsearch
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.106:9300

logging:
  level:
    root: warn
    com.star: info
  file: log/blog-pro.log

mybatis:
  type-aliases-package: com.li.blog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true







